services:
  postgres:
    image: postgres:latest
    container_name: postgres-feedback-db
    environment:
      POSTGRES_DB: tripfeedback
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "6432:5432"
    volumes:
      - postgres_feedback_data:/var/lib/postgresql/data

  app:
    image: shivaak/trip-feedback:latest
    ports:
      - "7001:7001"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://postgres-feedback-db:5432/tripfeedback
      DB_USERNAME: admin
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres

volumes:
  postgres_feedback_data:
